image: alpine:latest

pages:
  only:
    - master
  script:
    - echo 'probably we need some steps even if it is prebuilt lol'
    - mkdir imitation
    - cp -R build/ imitation/
  artifacts:
    paths:
    - build
  only:
    - master
